inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
   Max: 160

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
