inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160
  Exclude:
    - spec/integration/purl_spec.rb

Metrics/AbcSize:
  Max: 22

Metrics/ClassLength:
  Max: 205

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - app/models/purl_resource.rb
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
