stacks:
  url: 'https://stacks.stanford.edu'
  url_b: 'https://sul-stacks-prod-b.stanford.edu'
  
flipbook:
  url: 'http://sul-reader.stanford.edu/flipbook2'
  auth_url: 'https://sul-reader.stanford.edu/flipbook2/auth'

document_cache_root: "<%= File.join(Rails.root, "document_cache") %>"

resource_cache:
  enabled: true
  lifetime: <%= 1.hour %>

purl_resource:
  mods: 'http://purl.stanford.edu/%{druid}.mods'
  public_xml: 'http://purl.stanford.edu/%{druid}.xml'
  iiif_manifest: 'http://purl.stanford.edu/%{druid}/iiif/manifest.json'

embed:
  url: 'http://purl.stanford.edu/%{druid}'
  url_template: 'http://purl.stanford.edu/embed.{format}{?url*,application_options*}'
  application_options:
    hide_title: true
    hide_metadata: true

searchworks:
  url: 'http://searchworks.stanford.edu/view/'

feedback:
  email_to: ""
